version: "3.8"

services:
    app:
        image: pytransfer
        container_name: pytransfer
        build: .
        command: sh -c "python manage.py makemigrations --noinput &&
                    python manage.py migrate --noinput &&
                    python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        container_name: Postgresql
        image: postgres:13
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data: