# Generated by Django 3.2.6 on 2021-11-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('nomecompleto', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pytransfer.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_destino', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Executando', 'Executando'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('auth_token', models.CharField(blank=True, max_length=100)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='pytransfer.pessoa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytransfer.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True)),
                ('tx_token', models.CharField(blank=True, default='', max_length=100)),
                ('cancelado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytransfer.pessoa')),
            ],
        ),
    ]
