# Generated by Django 3.2.6 on 2021-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0002_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='senha',
            field=models.CharField(default='passw0rd', max_length=100),
        ),
    ]
