# Generated by Django 3.2.6 on 2021-08-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0003_todo_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nomeCompleto',
            new_name='nomecompleto',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='sobreNome',
            new_name='sobrenome',
        ),
    ]
