# Generated by Django 3.2.6 on 2021-08-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0004_auto_20210806_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
