# Generated by Django 3.2.6 on 2021-08-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0005_alter_pessoa_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='token',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pytransfer.pessoa')),
            ],
        ),
    ]
