# Generated by Django 3.2.6 on 2021-08-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0007_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Executando', 'Executando'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('before', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True)),
                ('after', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True)),
                ('auth_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='history',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='pytransfer.pessoa'),
        ),
        migrations.AddField(
            model_name='history',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytransfer.pessoa'),
        ),
    ]
