# Generated by Django 3.2.6 on 2021-08-06 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0009_alter_history_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
