# Generated by Django 3.2.6 on 2021-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0010_auto_20210806_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='cliente',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='pessoa',
            new_name='remetente',
        ),
        migrations.RemoveField(
            model_name='history',
            name='after',
        ),
        migrations.RemoveField(
            model_name='history',
            name='before',
        ),
        migrations.AddField(
            model_name='balance',
            name='tx_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
