# Generated by Django 3.2.6 on 2021-08-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0011_auto_20210806_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
