# Generated by Django 3.2.6 on 2021-08-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytransfer', '0013_remove_history_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='token_destino',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
