name: Django application

on:
  push:
    branches: ['main', 'development', 'sourcery/main']
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install depedencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python3 manage.py migrate

    - name: Run tests
      run: python3 manage.py test

    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py tests

    - name: Django
      run: |
        python3 manage.py test