name: Django Tests

on:
  push:
    branches: 
      ['main', 'development']
      
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: SetUp Python3.8
      uses: actions/setup-python@v2 
      with:
        python-version: 3.8
  
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    
    - name: Coverage report
      run: |
        pip intall coverage
        coverage run manage.py tests
    
    - name: Django
      run: |
        python3 manage.py test